### ISSUE TITLE
watch recursively fail on linux

### ISSUE THREAD

**Issue by MaskeZen** [antonk52/synd#30]
Hello, this fails in Linux, node version 16.15.1

```
node:fs:2262
    throw new ERR_FEATURE_UNAVAILABLE_ON_PLATFORM('watch recursively');
    ^

TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
    at new NodeError (node:internal/errors:372:5)
    at Object.watch (node:fs:2262:11)
```

https://nodejs.org/docs/latest/api/fs.html#fs_caveats

**Comment by antonk52** [comment]
Hello and thank you for reporting this!

I have only used this on macos in the past. Thanks for attaching the link to nodejs docs for the issue source. This should be a fairly straightforward fix by replacing fs.watch with [chokidar](https://www.npmjs.com/package/chokidar) around [here](https://github.com/antonk52/synd/blob/main/src/syndProcess.ts#L69).

I am unlikely have the time to fix and test this  soon. Though if you send a PR, I am happy to merge it and release a new version 🙂

**Comment by MaskeZen** [comment]
great, I go to look that.
Thanks.

**Comment by antonk52** [comment]
The native support for recursive file watching was added to [nodejs v19.1.0](https://github.com/nodejs/node/releases/tag/v19.1.0).
